import 'package:flutter/material.dart';
import '../premium_ui.dart';
import '../services/radar_service.dart';
import '../services/radar_survey_service.dart';
import '../services/location_service.dart';
import '../services/solar_context_service.dart';
import 'species_screen.dart';
import 'species_detail_screen.dart';
import 'premium_animal_screen.dart';

class RadarPanel extends StatelessWidget {
  const RadarPanel({super.key,required this.snapshot,required this.onRefresh,this.loading=false,this.error=false});
  final RadarSnapshot? snapshot;
  final Future<void> Function() onRefresh;
  final bool loading,error;
  static String habitatLabel(String value)=>const {'forest':'Bosco','meadow':'Prati','rock':'Rocce','wetland':'Zone umide','water':'Acqua','farmland':'Campagne','urban':'Area urbana','park':'Parco alberato','scrub':'Macchia','mosaic':'Mosaico di habitat','unknown':'Habitat non disponibile'}[value]??value;
  @override
  Widget build(BuildContext context){
    final data=snapshot;
    return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
      Row(children:[const Expanded(child:Text('WildTrack Radar',style:TextStyle(fontFamily:'serif',fontSize:21,fontWeight:FontWeight.w800))),IconButton(tooltip:'Aggiorna Radar',onPressed:loading?null:onRefresh,icon:const Icon(Icons.refresh)),IconButton(tooltip:'Dati e limiti del Radar',onPressed:()=>_sources(context),icon:const Icon(Icons.info_outline))]),
      const Text('Condizioni favorevoli, non probabilità di incontro',style:TextStyle(fontSize:11,color:WildColors.muted)),
      if(loading)const Padding(padding:EdgeInsets.symmetric(vertical:8),child:LinearProgressIndicator()),
      if(error)const Padding(padding:EdgeInsets.symmetric(vertical:8),child:Text('Radar non disponibile. Riprova: nessun valore dimostrativo viene mostrato.')),
      if(data!=null&&!data.hasPosition)...[
        const Padding(padding:EdgeInsets.symmetric(vertical:10),child:Text('Serve una posizione recente e affidabile per suggerire specie nella tua zona.')),
        OutlinedButton.icon(onPressed:()async{await LocationService.ensurePermission();await onRefresh();},icon:const Icon(Icons.my_location),label:const Text('Autorizza e aggiorna posizione')),
      ],
      if(data?.hasPosition==true)...[
        Padding(padding:const EdgeInsets.symmetric(vertical:8),child:Text('${data!.solar?.label??'Fase solare non disponibile'} · ${habitatLabel(data.habitat)}\nAggiornato ${SolarContext.clock(data.generatedAt)} · ${data.weatherAvailable?'meteo disponibile':'meteo non disponibile'}',style:const TextStyle(fontSize:11,height:1.4,color:WildColors.muted))),
        Text(data.solar?.dark==true?'Avvistamento visivo al buio: condizioni limitate':'Specie da osservare adesso',style:const TextStyle(fontWeight:FontWeight.w800)),
        if(data.species.isEmpty)const Padding(padding:EdgeInsets.symmetric(vertical:10),child:Text('Nessuna specie con condizioni sufficienti dai dati disponibili. Non significa assenza di fauna.')),
        if(data.species.isNotEmpty)_strip(context,data.species.take(4).toList(),false),
        if(data.listening.isNotEmpty)...[const SizedBox(height:10),const Text('Da ascoltare · senza richiami',style:TextStyle(fontWeight:FontWeight.w800)),_strip(context,data.listening.take(3).toList(),true)],
        Wrap(spacing:8,children:[TextButton.icon(onPressed:()=>_all(context),icon:const Icon(Icons.radar),label:const Text('Tutti i risultati')),TextButton.icon(onPressed:()=>_survey(context),icon:const Icon(Icons.fact_check_outlined),label:const Text('Registra controllo'))]),
      ],
    ]);
  }
  Widget _strip(BuildContext context,List<RadarSpecies> rows,bool listening)=>SizedBox(height:214,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:rows.length,separatorBuilder:(_,__)=>const SizedBox(width:8),itemBuilder:(_,i){final row=rows[i],detail=speciesDetails[row.name]!;return SizedBox(width:148,child:Material(color:Colors.white,borderRadius:BorderRadius.circular(18),child:InkWell(onTap:()=>_explain(context,row,listening),borderRadius:BorderRadius.circular(18),child:Padding(padding:const EdgeInsets.all(9),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Image.asset('${detail.newArtwork?'assets/radar_species':'assets/approved'}/${detail.asset}_hero.jpg',fit:BoxFit.contain,filterQuality:FilterQuality.high)),const SizedBox(height:5),Text(row.name,style:const TextStyle(fontFamily:'serif',fontWeight:FontWeight.w800,fontSize:15)),Text(listening?'Ascolto passivo':'Condizioni ${row.conditions.toLowerCase()}',style:const TextStyle(fontWeight:FontWeight.w700,fontSize:12)),Text(row.presenceSupported?'Segnalazioni nella zona':'Presenza da confermare',style:const TextStyle(fontSize:10,color:WildColors.muted)),const SizedBox(height:5),const Text('Perché questo suggerimento ›',style:TextStyle(fontSize:10,color:WildColors.forest))])))));}));
  void _explain(BuildContext context,RadarSpecies row,bool listening)=>showModalBottomSheet<void>(context:context,isScrollControlled:true,backgroundColor:WildColors.ivory,builder:(c)=>SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisSize:MainAxisSize.min,children:[Text(row.name,style:WildText.display),const SizedBox(height:10),Text(listening?'Ascolto passivo suggerito':'Condizioni ${row.conditions.toLowerCase()} · indice ${row.score}/100'),Text('Completezza dati: ${row.quality.toLowerCase()}',style:const TextStyle(color:WildColors.muted)),const SizedBox(height:12),Text(row.reason,style:const TextStyle(height:1.5)),const SizedBox(height:12),Text(row.bestWindow),const SizedBox(height:12),const Text('Indice orientativo: non indica quanti animali ci sono né la probabilità di incontrarli. Segnalazioni recenti non garantiscono presenza attuale.',style:TextStyle(fontSize:12,color:WildColors.muted)),const SizedBox(height:12),FilledButton(onPressed:(){Navigator.pop(c);Navigator.push(context,MaterialPageRoute<void>(builder:(_)=>PremiumAnimalScreen(animals.firstWhere((a)=>a.name==row.name))));},child:const Text('Apri scheda completa'))]))));
  void _sources(BuildContext context){final s=snapshot;showModalBottomSheet<void>(context:context,isScrollControlled:true,builder:(_)=>SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisSize:MainAxisSize.min,children:[const Text('Dati del Radar',style:WildText.display),Text('Posizione: ${s?.hasPosition==true?'recente, accuratezza ≤200 m':'non disponibile o insufficiente'}'),Text('Meteo Open-Meteo: ${s?.weatherAvailable==true?'aggiornato ${SolarContext.clock(s?.weatherAt)}':'non disponibile'}'),Text('Habitat © OpenStreetMap contributors · ODbL: ${habitatLabel(s?.habitat??'unknown')}. Contesto entro 1,4 km, non habitat esatto del punto.'),Text('Quota: ${s?.elevation?.round().toString()??'non affidabile'}${s?.elevation==null?'':' m'}'),const SizedBox(height:10),const Text('Il calcolo combina fase solare, stagionalità, habitat, quota disponibile, meteo e segnalazioni. Le regole editoriali non sono un modello statistico validato.'),const SizedBox(height:10),Text('Evidenze regionali: ${s?.evidenceAvailable==true?'dati disponibili':'nessuna evidenza recente disponibile'}. Archivio personale entro 25 km/365 giorni; campione GBIF entro 40 km/730 giorni; Community pubblica non verificata. Assenza di record non equivale ad assenza della specie.'),const SizedBox(height:10),const Text('I controlli sul campo confrontano visite entro 2 km, stessa fase solare e ultimi 90 giorni. Sono conteggi descrittivi, non una probabilità. Le passeggiate senza avvistamenti non sono controlli negativi automatici.'),const SizedBox(height:10),const Text('Le fototrappole non sono collegate: occorre una sorgente autorizzata. Non vengono simulate. Il Radar non pubblica la tua posizione; coordinate inviate ai servizi meteo, cartografici e GBIF per leggere il contesto.'),const SizedBox(height:10),const Text('Alba e tramonto sono approssimazioni astronomiche: rilievi, nuvole e ostacoli cambiano la luce effettiva.')]))));}
  void _all(BuildContext context)=>Navigator.push(context,MaterialPageRoute<void>(builder:(c)=>Scaffold(appBar:AppBar(title:const Text('Risultati Radar')),body:ListView(padding:const EdgeInsets.all(16),children:[const Text('Ordine per condizioni favorevoli. Le specie escluse dal contesto restano consultabili nel catalogo.'),for(final row in snapshot?.species??const <RadarSpecies>[])ListTile(title:Text(row.name),subtitle:Text('${row.conditions} · ${row.quality.toLowerCase()} completezza dati\n${row.bestWindow}'),isThreeLine:true,trailing:const Icon(Icons.chevron_right),onTap:()=>_explain(c,row,false)),TextButton(onPressed:()=>Navigator.push(c,MaterialPageRoute<void>(builder:(_)=>const SpeciesScreen())),child:const Text('Catalogo completo · 31 specie'))]))));
  Future<void> _survey(BuildContext context)async{
    final s=snapshot;if(s?.latitude==null||s?.longitude==null)return;
    var name=s!.species.firstOrNull?.name??animals.first.name, minutes=20,seen=false;
    final confirmed=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:const Text('Controllo sul campo'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('Registra solo una ricerca effettiva in questa posizione. “Non osservata” non significa assente.'),DropdownButton<String>(isExpanded:true,value:name,items:animals.map((a)=>DropdownMenuItem(value:a.name,child:Text(a.name))).toList(),onChanged:(v)=>set(()=>name=v!)),DropdownButton<int>(value:minutes,items:[5,10,15,20,30,45,60,90,120].map((n)=>DropdownMenuItem(value:n,child:Text('$n minuti'))).toList(),onChanged:(v)=>set(()=>minutes=v!)),SwitchListTile(title:Text(seen?'Specie osservata':'Specie non osservata'),value:seen,onChanged:(v)=>set(()=>seen=v))])),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Annulla')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Salva'))])));
    if(confirmed!=true)return;
    try{await RadarSurveyService.instance.add(RadarSurvey(species:name,latitude:s.latitude!,longitude:s.longitude!,at:DateTime.now(),minutes:minutes,seen:seen,phase:s.solar?.phase??'unknown'));await onRefresh();if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Controllo salvato. Le foto e gli avvistamenti si registrano separatamente.')));}catch(_){if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Controllo non salvato. Riprova.')));}
  }
}
