// One explicit record per catalogue species. Shared rendering is in PremiumAnimalScreen.
class SpeciesDetail {
  const SpeciesDetail({
    required this.asset,
    required this.size,
    required this.mass,
    required this.activity,
    required this.tags,
    required this.signs,
    required this.seasons,
    required this.photo,
    required this.source,
    this.badge,
    this.status = 'Consulta la valutazione nella fonte',
    this.note = '',
  });
  final String asset, size, mass, activity, photo, source, status, note;
  final String? badge;
  final List<String> tags, seasons;
  final List<(String, String)> signs;
}

const speciesDetails = <String, SpeciesDetail>{
  "Cervo": SpeciesDetail(
    asset: "cervo",
    size: "180–250 cm",
    mass: "120–250 kg",
    activity: "Alba e tramonto",
    tags: ["Foreste", "Aree montane", "Radure e pascoli"],
    signs: [
      ("Impronta", "Zoccolo ovale con due unghioni; leggi anche la pista."),
      ("Fatte", "Pellet scuri raggruppati; forma variabile con la dieta."),
      ("Sfregamenti", "Corteccia consumata dai palchi su giovani tronchi."),
      (
        "Palchi",
        "Ramificati e rinnovati ogni anno; lascia i reperti sul posto.",
      ),
    ],
    seasons: ["Radure", "Ore fresche", "Bramito", "Piste sulla neve"],
    photo: "Inquadra il cervo da un punto riparato, con teleobiettivo e senza avvicinarti al branco.",
    source: "https://www.parcoabruzzo.it/fauna.schede.dettaglio.php?id=313",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Capriolo": SpeciesDetail(
    asset: "capriolo",
    size: "90–130 cm",
    mass: "10–27 kg",
    activity: "Radure nelle ore tranquille",
    tags: ["Margini boschivi", "Radure", "Campagne"],
    signs: [
      (
        "Impronta",
        "Piccoli unghioni appuntiti; confronta la pista con il cervo.",
      ),
      (
        "Fatte",
        "Piccoli pellet scuri; il solo aspetto non basta a identificarli.",
      ),
      ("Sfregamenti", "Segni sui giovani fusti; valuta altezza e contesto."),
      ("Palchi", "Corti, spesso con tre punte nei maschi adulti."),
    ],
    seasons: ["Radure", "Amori estivi", "Margini boschivi", "Manto grigio"],
    photo: "Aspetta ai margini del bosco e fotografa senza entrare nelle aree dove i piccoli riposano.",
    source: "https://www.areeprotettealpimarittime.it/fauna/capriolo",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Volpe": SpeciesDetail(
    asset: "volpe",
    size: "65–75 cm",
    mass: "Corpo, coda esclusa",
    activity: "Soprattutto crepuscolo e notte",
    tags: ["Boschi", "Campagne", "Periferie"],
    signs: [
      (
        "Impronta",
        "Quattro dita con unghie: è simile a quella di altri canidi.",
      ),
      (
        "Fatte",
        "Possono contenere peli o semi; evita attribuzioni da un solo reperto.",
      ),
      (
        "Tane",
        "Ingressi nel terreno; osserva senza avvicinarti né appostarti davanti.",
      ),
      (
        "Peli",
        "Pelo rossastro e coda folta sono indizi da associare a foto e pista.",
      ),
    ],
    seasons: ["Margini", "Ore fresche", "Frutti e bacche", "Piste sulla neve"],
    photo: "Fotografa a distanza con tempi rapidi; non attirare la volpe con cibo e non inseguirla.",
    source: "https://bur.regione.veneto.it/BurvServices/pubblica/burvGalleryDettaglio.aspx?id=593",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Camoscio alpino": SpeciesDetail(
    asset: "camoscio",
    size: "100–130 cm",
    mass: "70–90 cm al garrese",
    activity: "Versanti aperti, senza disturbo",
    tags: ["Rocce", "Pascoli alpini", "Boschi ripidi"],
    signs: [
      (
        "Impronta",
        "Due unghioni; forma e dimensioni cambiano con terreno e passo.",
      ),
      (
        "Fatte",
        "Pellet da ungulato: senza altri indizi non distinguono la specie.",
      ),
      (
        "Passaggi",
        "Piste su pendii e cenge; non seguire gli animali fuori sentiero.",
      ),
      ("Corna", "Sottili e uncinate; permanenti, non palchi caduti ogni anno."),
    ],
    seasons: ["Versanti", "Alta quota", "Amori", "Risparmio energia"],
    photo: "Usa un teleobiettivo dal sentiero e lascia libera la via di fuga, soprattutto con neve.",
    source: "https://www.pngp.it/fr/node/3559",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Stambecco": SpeciesDetail(
    asset: "stambecco",
    size: "Circa 160 cm ♂",
    mass: "Circa 90 kg ♂",
    activity: "Pendii rocciosi e pascoli",
    tags: ["Rocce", "Praterie alpine", "Alta quota"],
    signs: [
      (
        "Impronta",
        "Due unghioni da caprino; leggi l’intera pista su neve o terra.",
      ),
      ("Fatte", "Pellet scuri nei pascoli; il solo reperto non è diagnostico."),
      ("Corna", "Nei maschi sono grandi, arcuate e con rilievi anteriori."),
      (
        "Passaggi",
        "Cenge e rocce frequentate; lascia sempre libero il percorso.",
      ),
    ],
    seasons: ["Pascoli", "Alta quota", "Versanti", "Amori"],
    photo: "Cura sfondo e profilo delle corna; resta lontano anche quando lo stambecco sembra confidente.",
    source: "https://www.pngp.it/natura-e-ricerca/fauna/praterie-e-ambienti-rocciosi/lo-stambecco",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Cinghiale": SpeciesDetail(
    asset: "cinghiale",
    size: "100–150 cm",
    mass: "Corpo robusto",
    activity: "Notte e crepuscolo",
    tags: ["Boschi", "Macchia", "Campagne"],
    signs: [
      (
        "Impronta",
        "Due unghioni; nel fango possono apparire anche gli speroni.",
      ),
      (
        "Fatte",
        "Aspetto variabile con dieta e stagione: considera altri segni.",
      ),
      ("Grufolate", "Suolo rivoltato dal grugno durante la ricerca di cibo."),
      (
        "Insogli",
        "Pozze di fango usate per bagnarsi; possibili sfregamenti vicini.",
      ),
    ],
    seasons: ["Boschi", "Pozze di fango", "Ghiande", "Piste"],
    photo: "Fotografa da lontano, senza avvicinarti ai piccoli né bloccare una via di fuga.",
    source: "https://www.gransassolagapark.it/pagina.php?id=261",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Aquila reale": SpeciesDetail(
    asset: "aquila",
    size: "76–93 cm",
    mass: "3–6,6 kg",
    activity: "Volo planato sulle correnti",
    tags: ["Pareti rocciose", "Praterie", "Montagna"],
    signs: [
      (
        "Impronta",
        "Dita con artigli da rapace; lo schema non identifica la specie da solo.",
      ),
      (
        "Penne",
        "Grandi remiganti: una penna isolata richiede verifica esperta.",
      ),
      ("Posatoi", "Rocce dominanti utilizzate come punti di osservazione."),
      ("Giovani", "Bianco su ali e coda nei giovani; varia con l’età."),
    ],
    seasons: ["Territorio", "Volo planato", "Dispersione", "Presente"],
    photo: "Segui la silhouette con autofocus continuo e tempi rapidi; non cercare né fotografare il nido da vicino.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/aquila-reale",
    badge: "NT",
    status: "Quasi minacciata · Italia",
    note: "",
  ),
  "Grifone": SpeciesDetail(
    asset: "grifone",
    size: "Circa 100 cm",
    mass: "7,3–11,2 kg",
    activity: "Volo sulle correnti ascensionali",
    tags: ["Falesie", "Spazi aperti", "Prealpi"],
    signs: [
      (
        "Impronta",
        "Dita con artigli da rapace; lo schema non identifica la specie da solo.",
      ),
      ("Penne", "Remiganti grandi e scure; non attribuirle senza confronto."),
      ("Colonie", "Gruppi sulle pareti; osserva dai punti autorizzati."),
      (
        "Alimentazione",
        "Consuma carcasse: non avvicinarti ai punti di alimentazione.",
      ),
    ],
    seasons: ["Termiche", "Volo planato", "Gruppi", "Presente"],
    photo: "Usa il cielo o le pareti come sfondo e fotografa dai punti consentiti senza disturbare la colonia.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/grifone",
    badge: "NT",
    status: "Cattivo · Italia",
    note: "",
  ),
  "Poiana": SpeciesDetail(
    asset: "poiana",
    size: "51–57 cm",
    mass: "0,5–1,4 kg",
    activity: "Posatoi e volo diurno",
    tags: ["Campagne", "Colline", "Margini forestali"],
    signs: [
      (
        "Impronta",
        "Dita con artigli da rapace; lo schema non identifica la specie da solo.",
      ),
      ("Penne", "Penne barrate: confronta misura e disegno con altre specie."),
      ("Posatoi", "Alberi, pali e margini dei campi utilizzati per cacciare."),
      (
        "Richiamo",
        "Richiamo acuto e lamentoso; confrontalo con l’audio verificato.",
      ),
    ],
    seasons: ["Territori", "Volo", "Passaggi", "Svernanti"],
    photo: "Fotografa da un luogo sicuro ai margini dei campi; non sostare sulla carreggiata per seguire un posatoio.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/poiana",
    badge: "LC",
    status: "Favorevole · Italia",
    note: "",
  ),
  "Allocco": SpeciesDetail(
    asset: "allocco",
    size: "37–43 cm",
    mass: "81–96 cm apertura",
    activity: "Prevalentemente notturno",
    tags: ["Boschi maturi", "Parchi", "Cavità arboree"],
    signs: [
      (
        "Borre",
        "Rigurgiti con ossa e peli non digeriti, da verificare sul posto.",
      ),
      ("Penne", "Piumaggio bruno o grigio; non identifica da solo la specie."),
      ("Cavità", "Usa cavità degli alberi; non ispezionare il rifugio."),
      ("Capo", "Testa rotonda, occhi scuri e assenza di ciuffi auricolari."),
    ],
    seasons: ["Richiami", "Bosco", "Territorio", "Presente"],
    photo: "Sfrutta la luce naturale residua e alza gli ISO; evita flash, torce puntate e richiami riprodotti.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/allocco",
    badge: "LC",
    status: "Minor preoccupazione · Italia",
    note: "",
  ),
  "Picchio nero": SpeciesDetail(
    asset: "picchio",
    size: "45–47 cm",
    mass: "255–315 g",
    activity: "Richiami e tambureggiamento",
    tags: ["Boschi maturi", "Legno morto", "Faggete"],
    signs: [
      (
        "Scavi",
        "Cavità e scavi nel legno; più specie possono usare lo stesso albero.",
      ),
      ("Trucioli", "Legno appena staccato vicino agli scavi alimentari."),
      ("Penne", "Nere; associa il reperto all’osservazione del capo rosso."),
      (
        "Tamburo",
        "Tambureggiamento sui tronchi; distinto dal richiamo in volo.",
      ),
    ],
    seasons: ["Tamburo", "Bosco", "Presente", "Presente"],
    photo: "Attendi su un sentiero e usa tempi rapidi per il movimento; evita di sostare davanti alle cavità.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/picchio-nero",
    badge: "LC",
    status: "Inadeguato · Italia",
    note: "",
  ),
  "Airone cenerino": SpeciesDetail(
    asset: "airone",
    size: "90–98 cm",
    mass: "1–2 kg",
    activity: "Caccia in acqua bassa",
    tags: ["Zone umide", "Fiumi", "Lagune"],
    signs: [
      (
        "Impronta",
        "Dita lunghe nel fango delle sponde; confronta le dimensioni.",
      ),
      (
        "Penne",
        "Grigie e bianche; la sola penna non distingue tutti gli aironi.",
      ),
      ("Caccia", "Resta immobile o avanza lentamente cercando prede."),
      ("Volo", "Collo ripiegato e zampe protratte dietro il corpo."),
    ],
    seasons: ["Zone umide", "Acque basse", "Passaggi", "Svernanti"],
    photo: "Fotografa dai capanni all’altezza dell’acqua; anticipa lo scatto quando il becco punta verso la preda.",
    source:
        "https://www.lipu.it/uccelli/conoscerli-proteggerli/airone-cenerino",
    badge: "LC",
    status: "Inadeguato · Italia",
    note: "",
  ),
  "Germano reale": SpeciesDetail(
    asset: "germano",
    size: "50–65 cm",
    mass: "600–1.490 g",
    activity: "Acque basse e superficie",
    tags: ["Laghi", "Fiumi", "Paludi"],
    signs: [
      ("Impronta", "Piede palmato: altre anatre possono lasciare orme simili."),
      (
        "Penne",
        "Specchio alare blu-violetto; controlla anche gli altri caratteri.",
      ),
      (
        "Maschio",
        "Testa verde nel piumaggio riproduttivo; l’aspetto cambia con la muta.",
      ),
      (
        "Femmina",
        "Bruna screziata; distinguila da altre anatre con più dettagli.",
      ),
    ],
    seasons: ["Coppie", "Muta", "Gruppi", "Svernanti"],
    photo: "Abbassa il punto di ripresa senza uscire dal percorso e non usare pane per avvicinare le anatre.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/germano-reale",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Falco di palude": SpeciesDetail(
    asset: "falco",
    size: "48–56 cm",
    mass: "485–800 g",
    activity: "Volo basso sui canneti",
    tags: ["Canneti", "Paludi", "Zone umide"],
    signs: [
      (
        "Sagoma",
        "Ali lunghe, spesso tenute rialzate durante il volo di caccia.",
      ),
      ("Piumaggio", "Diverso per sesso ed età; documenta capo, ali e coda."),
      ("Caccia", "Perlustra i canneti con volo lento vicino alla vegetazione."),
      ("Penne", "Confronta disegno e misure: non basta un reperto isolato."),
    ],
    seasons: ["Passaggi", "Canneti", "Migrazione", "Svernanti"],
    photo: "Segui il volo con autofocus continuo dal capanno; lascia integri i canneti e non cercare i nidi.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/falco-palude",
    badge: "LC",
    status: "Favorevole · Italia",
    note: "",
  ),
  "Orso bruno": SpeciesDetail(
    asset: "orso",
    size: "150–180 cm ♂*",
    mass: "140–210 kg ♂*",
    activity: "Osservazione a grande distanza",
    tags: ["Boschi montani", "Radure", "Appennino e Alpi"],
    signs: [
      (
        "Impronta",
        "Cinque dita; osserva la pista senza seguirla verso l’animale.",
      ),
      (
        "Pietre",
        "Può rivoltare pietre per cercare insetti; non è un segno esclusivo.",
      ),
      ("Fatte", "Contenuto variabile con frutti, insetti e altri alimenti."),
      ("Peli", "Peli su vegetazione o passaggi: documenta senza raccogliere."),
    ],
    seasons: ["Distanza", "Alimentazione", "Frutti", "Riposo"],
    photo: "Usa un lungo teleobiettivo dai punti autorizzati: non cercare di ridurre la distanza e non lasciare cibo.",
    source: "https://www.parcoabruzzo.it/scheda-orso.php",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "*Maschio di orso marsicano: dati riferiti alla popolazione appenninica, non a tutte le popolazioni di orso bruno.",
  ),
  "Lupo": SpeciesDetail(
    asset: "lupo",
    size: "110–148 cm",
    mass: "25–40 kg",
    activity: "Elusivo; avvistamenti rari",
    tags: ["Boschi", "Praterie", "Montagna"],
    signs: [
      (
        "Impronta",
        "Simile a un grosso cane; serve anche la sequenza della pista.",
      ),
      (
        "Fatte",
        "Possono contenere peli; evita di toccarle o identificarle da sole.",
      ),
      (
        "Pista",
        "Orme spesso allineate; la regolarità non è una prova definitiva.",
      ),
      (
        "Ululato",
        "Richiamo sociale: non usare l’audio per provocare risposte.",
      ),
    ],
    seasons: ["Elusivo", "Elusivo", "Elusivo", "Piste sulla neve"],
    photo: "Documenta più caratteri con il teleobiettivo; non inseguire, attirare o confondere un cane con un lupo.",
    source: "https://www.parcoabruzzo.it/fauna.schede.dettaglio.php?id=21",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Sciacallo dorato": SpeciesDetail(
    asset: "sciacallo",
    size: "Canide medio",
    mass: "Più piccolo del lupo",
    activity: "Documenta luogo e ora",
    tags: ["Campagne", "Boschi radi", "Nord-est"],
    signs: [
      ("Impronta", "Orma da canide, simile a volpe e cane: da sola non basta."),
      (
        "Mantello",
        "Mantello fulvo con sfumature grigie: valuta anche proporzioni.",
      ),
      ("Sagoma", "Muso affusolato e corporatura da canide medio."),
      (
        "Richiamo",
        "Vocalizzazioni da confrontare con registrazioni affidabili.",
      ),
    ],
    seasons: [
      "Presenza locale",
      "Presenza locale",
      "Presenza locale",
      "Presenza locale",
    ],
    photo: "Fotografa senza avvicinarti e annota luogo, ora e caratteri visibili; non attirarlo con cibo o audio.",
    source: "https://www.consiglio.regione.fvg.it/pagineinterne/Portale/comunicatiStampaDettaglio.aspx?ID=964510",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Marmotta": SpeciesDetail(
    asset: "marmotta",
    size: "53–73 cm",
    mass: "Coda 13–16 cm",
    activity: "Praterie alpine, di giorno",
    tags: ["Praterie alpine", "Tane", "Pascoli"],
    signs: [
      ("Tane", "Ingressi nel terreno; non ostruirli né appostarti davanti."),
      ("Impronta", "Pista da roditore; terreno e passo modificano il disegno."),
      ("Fischio", "Segnale d’allarme: fermati e aumenta la distanza."),
      ("Alimentazione", "Erbe e germogli nei pascoli intorno alle tane."),
    ],
    seasons: ["Risveglio", "Attiva", "Verso il letargo", "Letargo"],
    photo: "Riprendi da lontano all’altezza dell’animale e interrompi l’avvicinamento quando emette fischi d’allarme.",
    source: "https://www.pngp.it/natura-e-ricerca/fauna/praterie-e-ambienti-rocciosi/la-marmotta",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Ermellino": SpeciesDetail(
    asset: "ermellino",
    size: "24–29 cm",
    mass: "125–450 g",
    activity: "Rapido ed elusivo",
    tags: ["Rocce", "Pascoli", "Ambienti alpini"],
    signs: [
      ("Impronta", "Piccole orme da mustelide; verifica l’intera pista."),
      ("Coda", "Punta nera anche nel mantello invernale bianco."),
      ("Mantello", "Dorso bruno e ventre chiaro in estate; bianco in inverno."),
      ("Rifugi", "Anfratti e pietre: osserva senza smuovere né esplorare."),
    ],
    seasons: ["Cambio manto", "Manto bruno", "Cambio manto", "Manto bianco"],
    photo: "Prepara autofocus continuo e tempi rapidi; fotografa la punta della coda e non smuovere le pietre.",
    source: "https://www.pngp.it/natura-e-ricerca/fauna/carnivori/l-ermellino",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Tasso": SpeciesDetail(
    asset: "tasso",
    size: "Fino a circa 1 m*",
    mass: "Fino a 17 kg",
    activity: "Osserva senza sostare alle tane",
    tags: ["Boschi", "Coltivi", "Praterie"],
    signs: [
      (
        "Impronta",
        "Cinque dita e unghie; la pista aiuta a distinguere i mustelidi.",
      ),
      (
        "Tane",
        "Più ingressi e terra smossa: non entrare né bloccare i passaggi.",
      ),
      ("Muso", "Bande nere longitudinali sul fondo chiaro."),
      (
        "Piste",
        "Passaggi nella vegetazione; non creare appostamenti davanti alle tane.",
      ),
    ],
    seasons: ["Boschi", "Ore tranquille", "Boschi", "Presenza locale"],
    photo: "Sfrutta la luce naturale disponibile da lontano; evita flash e non presidiare gli ingressi delle tane.",
    source: "https://www.parchilazio.it/schede-32368-tasso_rimesso_in_natura_dai_guardiaparco",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "*Lunghezza comprensiva della coda.",
  ),
  "Gracchio alpino": SpeciesDetail(
    asset: "gracchio",
    size: "38 cm",
    mass: "168–246 g",
    activity: "Gruppi e volo in montagna",
    tags: ["Rocce", "Praterie alpine", "Alta quota"],
    signs: [
      (
        "Impronta",
        "Tre dita avanti e una dietro; la sola orma non distingue i corvidi.",
      ),
      ("Zampe", "Rosse negli adulti; controlla anche becco e sagoma."),
      ("Penne", "Nere; non distinguono da sole i corvidi."),
      ("Gruppi", "Volo sociale presso pareti e praterie di montagna."),
    ],
    seasons: ["Montagna", "Insetti", "Bacche", "Spostamenti"],
    photo: "Segui il volo con tempi rapidi e documenta il becco; non offrire cibo vicino a rifugi e sentieri.",
    source:
        "https://www.lipu.it/uccelli/conoscerli-proteggerli/gracchio-alpino",
    badge: "LC",
    status: "Inadeguato · Italia",
    note: "",
  ),
  "Gufo reale": SpeciesDetail(
    asset: "gufo",
    size: "60–75 cm",
    mass: "1,5–2,5 kg",
    activity: "Sera e notte, senza richiami",
    tags: ["Pareti rocciose", "Vallate", "Spazi aperti"],
    signs: [
      (
        "Impronta",
        "Piede con artigli; il dito esterno può ruotare indietro. Verifica anche gli altri segni.",
      ),
      (
        "Borre",
        "Rigurgiti con resti non digeriti: più rapaci producono borre.",
      ),
      ("Penne", "Mottate e barrate; non avvicinarti ai siti di riposo."),
      (
        "Richiamo",
        "Vocalizzazione territoriale profonda; non provocare risposte.",
      ),
    ],
    seasons: ["Territorio", "Distanza", "Territorio", "Presente"],
    photo: "Fotografa solo da lontano con luce naturale; evita flash e qualsiasi avvicinamento ai siti riproduttivi.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/gufo-reale",
    badge: "NT",
    status: "Quasi minacciata · Italia",
    note: "",
  ),
  "Barbagianni": SpeciesDetail(
    asset: "barbagianni",
    size: "33–35 cm",
    mass: "85–93 cm apertura",
    activity: "Notte nei paesaggi rurali",
    tags: ["Campagne", "Edifici rurali", "Cavità"],
    signs: [
      (
        "Impronta",
        "Piede con artigli; il dito esterno può ruotare indietro. Verifica anche gli altri segni.",
      ),
      (
        "Borre",
        "Resti di prede rigurgitati: documenta senza entrare nei rifugi.",
      ),
      ("Penne", "Piumaggio chiaro con dorso dorato; confronta più caratteri."),
      (
        "Stridio",
        "Vocalizzazione stridente, diversa dall’ululato di altri gufi.",
      ),
    ],
    seasons: ["Campagne", "Campagne", "Campagne", "Presenza locale"],
    photo: "Usa luce naturale residua e ISO elevati; osserva dall’esterno e non entrare negli edifici occupati.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/barbagianni",
    badge: "LC",
    status: "Cattivo · Italia",
    note: "",
  ),
  "Ghiandaia": SpeciesDetail(
    asset: "ghiandaia",
    size: "34–35 cm",
    mass: "125–205 g",
    activity: "Boschi e ambienti alberati",
    tags: ["Boschi", "Querceti", "Parchi"],
    signs: [
      (
        "Impronta",
        "Tre dita avanti e una dietro; la sola orma non distingue i corvidi.",
      ),
      ("Penne", "Le piccole penne azzurre sono un indizio da verificare."),
      ("Capo", "Documenta disegno del capo e area scura vicino al becco."),
      (
        "Richiami",
        "Vocalizzazioni forti e varie, ascoltabili nella sezione Versi.",
      ),
    ],
    seasons: ["Boschi", "Boschi", "Boschi", "Boschi"],
    photo: "Attendi in silenzio e riprendi il pannello azzurro dell’ala; evita di inseguirla fra gli alberi.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/ghiandaia",
    badge: "LC",
    status: "Favorevole · Italia",
    note: "",
  ),
};
