// One explicit record per catalogue species. Shared rendering is in PremiumAnimalScreen.
class SpeciesDetail {
  const SpeciesDetail({
    required this.asset,
    required this.size,
    required this.mass,
    required this.activity,
    required this.tags,
    required this.signs,
    required this.seasons,
    required this.photo,
    required this.source,
    required this.habitat,
    required this.seasonLevels,
    this.badge,
    this.status = 'Consulta la valutazione nella fonte',
    this.note = '',
    this.bestPeriod = '', this.diet = '', this.breeding = '', this.voiceDescription = '', this.newArtwork = false,
  });
  final String asset, size, mass, activity, photo, source, status, note;
  final String bestPeriod, diet, breeding, voiceDescription;
  final bool newArtwork;
  final String habitat;

  /// Editorial ordinal levels: 0 dormant, 1 low, 2 medium, 3 high, 4 very high.
  /// Not percentages and not predictions from local observation data.
  final List<int> seasonLevels;
  final String? badge;
  final List<String> tags, seasons;
  final List<(String, String)> signs;
}

const speciesDetails = <String, SpeciesDetail>{
"Lince": SpeciesDetail(
asset: "lince",
size: "Corpo 80–130 cm · coda 15–25 cm",
mass: "Circa 15–30 kg",
activity: "Crepuscolo e notte",
photo: "Teleobiettivo, AF-C e tempo iniziale 1/1000 s. Scatta dal punto in cui ti trovi, lascia una via di fuga e non seguire l’animale.",
source: "https://www.kora.ch/en/species/lynx/profile",
habitat: "Foreste estese con sottobosco, rocce e zone tranquille. La distribuzione è frammentata: habitat adatto non significa presenza certa. Nelle Alpi e nelle Prealpi l’osservazione diretta è rara.",
bestPeriod: "Le tracce sulla neve possono essere osservabili in inverno; l’attività aumenta nel periodo degli amori fra fine inverno e inizio primavera. Gli incontri restano eccezionali: osserva dai percorsi esistenti.",
diet: "Soprattutto caprioli e altri ungulati di taglia adatta; anche lepri e piccoli vertebrati, secondo le risorse locali.",
breeding: "Accoppiamento a fine inverno; i piccoli nascono in primavera dopo circa due mesi di gestazione e restano con la madre fino alla stagione seguente.",
voiceDescription: "Normalmente silenziosa. Miagolii e vocalizzazioni possono accompagnare il periodo degli amori; non usare richiami per provocare risposte.",
tags: ["Foreste tranquille", "Rocce", "Grande territorio"], seasons: ["Primavera: tracce e attività riproduttiva, senza cercare le tane.", "Estate: ripari forestali; avvistamenti molto rari.", "Autunno: margini tranquilli, crepuscolo.", "Inverno: piste sulla neve, senza seguirle fino ai rifugi."], seasonLevels: [2, 1, 1, 2],
newArtwork: true, signs: [("Impronta","Quattro dita e cuscinetto ampio; unghie in genere non impresse. Confronta pista, scala e forma, senza attribuire una singola orma."),("Fatte","Segmentate, con peli e residui ossei; non diagnostiche da sole. Non toccarle."),("Ciuffi","Ciuffi scuri all’estremità delle orecchie; valuta anche la forma del capo."),("Coda","Corta con punta nera, carattere utile insieme alle proporzioni del corpo.")],
),
"Tritone": SpeciesDetail(
asset: "tritone",
size: "Circa 7–12 cm",
mass: "Pochi grammi · variabile con sesso e stagione",
activity: "Acquatico in primavera; terrestre soprattutto di notte",
photo: "Ripresa dal bordo, luce naturale e polarizzatore se utile. Metti a fuoco l’occhio; non spostare l’animale né sollevarlo per mostrare il ventre.",
source: "https://www.froglife.org/info-advice/amphibians-and-reptiles/alpine-newt/",
habitat: "La scheda riguarda il tritone alpestre. Stagni, pozze e piccoli specchi d’acqua senza pesci, con boschi e rifugi umidi nelle vicinanze. Negli ambienti alpini i tempi riproduttivi dipendono da quota e disgelo.",
bestPeriod: "Primavera e inizio estate nelle pozze riproduttive; a quota elevata dopo il disgelo. Osserva dall’esterno, senza entrare in acqua o usare retini.",
diet: "Piccoli invertebrati acquatici e terrestri; la dieta varia con fase di vita e habitat.",
breeding: "Fecondazione interna tramite spermatofora. La femmina depone le uova singolarmente, spesso ripiegandole nelle foglie sommerse; le larve hanno branchie esterne.",
voiceDescription: "Non ha un canto di richiamo paragonabile a rane e rospi. L’assenza di un pulsante audio è intenzionale.",
tags: ["Stagni", "Boschi umidi", "Pozze montane"], seasons: ["Primavera: ingresso in acqua e corteggiamento.", "Estate: larve e permanenza acquatica variabile con quota.", "Autunno: fase terrestre nei rifugi umidi.", "Inverno: riposo in siti protetti, secondo il clima."], seasonLevels: [4, 3, 2, 0],
newArtwork: true, signs: [("Ventre","Arancione in genere uniforme; osservabile soltanto senza manipolazione."),("Coda","Compressa lateralmente, adatta al nuoto; non basta da sola per identificare la specie."),("Uova","Uova singole avvolte nella vegetazione sommersa; non aprire le foglie."),("Larve","Branchie esterne ai lati del capo. Distinguile con cautela dalle larve di altre salamandre.")],
),
"Rospo": SpeciesDetail(
asset: "rospo",
size: "Circa 5–15 cm · femmine più grandi",
mass: "Variabile, da decine a oltre 100 g negli adulti",
activity: "Crepuscolo e notte, soprattutto con umidità",
photo: "Abbassa il punto di ripresa e usa luce naturale. Per un soggetto fermo prova 1/250 s; non bagnarlo artificialmente e non spostarlo sul sentiero.",
source: "https://www.parcoforestecasentinesi.it/it/natura/biodiversita/la-fauna/anfibi-e-rettili-nel-parco-nazionale-0",
habitat: "La scheda riguarda il rospo comune. Boschi, prati, siepi e giardini con rifugi freschi; per riprodursi raggiunge stagni e raccolte d’acqua. Le migrazioni possono attraversare strade.",
bestPeriod: "Sere umide di primavera durante la migrazione e le deposizioni; anche sere miti di estate e autunno. Mantieni distanza e attenzione sulle strade.",
diet: "Insetti, lombrichi, lumache e altri invertebrati; non alimentarlo e non raccoglierlo.",
breeding: "Accoppiamento con il maschio sul dorso della femmina. Uova deposte in lunghi cordoni gelatinosi; i girini sono acquatici e metamorfosano in piccoli rospi.",
voiceDescription: "Il maschio emette richiami brevi e discreti, anche di rilascio. Evita di provocare vocalizzazioni toccando l’animale.",
tags: ["Boschi", "Stagni", "Sere umide"], seasons: ["Primavera: migrazione e cordoni di uova.", "Estate: attività notturna nei giorni umidi.", "Autunno: alimentazione e ricerca di rifugi.", "Inverno: riposo in rifugi protetti."], seasonLevels: [4, 3, 2, 0],
newArtwork: true, signs: [("Pelle","Verrucosa con ghiandole parotoidi dietro agli occhi; le secrezioni difensive non vanno toccate."),("Occhio","Iride ramata e pupilla orizzontale; osserva senza illuminare direttamente."),("Uova","Cordoni gelatinosi lunghi, diversi dagli ammassi tipici di molte rane."),("Girini","Generalmente scuri, spesso in gruppi; l’aspetto da solo non certifica la specie.")],
),
"Salamandra": SpeciesDetail(
asset: "salamandra",
size: "Circa 15–25 cm",
mass: "Decine di grammi · variabile con taglia",
activity: "Notte e giornate molto umide",
photo: "Inquadra dal livello del soggetto con luce naturale diffusa. Proteggi i riflessi del mantello nero; non toccare o spostare l’animale.",
source: "https://www.parcoforestecasentinesi.it/it/natura/biodiversita/la-fauna/anfibi-e-rettili-nel-parco-nazionale-0",
habitat: "La scheda riguarda la salamandra pezzata. Boschi freschi di latifoglie, lettiera umida, ruscelli e pozze con acqua pulita. Non va confusa con la salamandra alpina, nera e con diversa biologia riproduttiva.",
bestPeriod: "Sere piovose e miti di primavera e autunno; talvolta di giorno dopo la pioggia. Osserva sui sentieri senza sollevare tronchi o pietre.",
diet: "Invertebrati come lombrichi, larve di insetti e piccoli molluschi; le larve predano organismi acquatici.",
breeding: "Nelle popolazioni locali la femmina rilascia larve già sviluppate in acqua, spesso in ruscelli e pozze. Le larve restano acquatiche fino alla metamorfosi.",
voiceDescription: "Non ha un canto territoriale simile a quello delle rane. Non inventare né riprodurre un verso di richiamo.",
tags: ["Boschi freschi", "Ruscelli", "Pioggia"], seasons: ["Primavera: attività con pioggia e rilascio delle larve.", "Estate: rifugi freschi; attività dopo piogge.", "Autunno: osservabile nelle sere umide e miti.", "Inverno: rifugi protetti; attività dipendente dal clima."], seasonLevels: [4, 2, 4, 1],
newArtwork: true, signs: [("Mantello","Macchie gialle irregolari su fondo nero; distinguile da altri anfibi senza manipolazione."),("Coda","Lunga e arrotondata, diversamente dalla coda appiattita di molti tritoni acquatici."),("Larve","Branchie esterne e piccoli arti; nei ruscelli osserva senza smuovere il fondo."),("Rifugi","Lettiera e legno morto conservano umidità: non sollevarli per cercare individui.")],
),

  "Cervo": SpeciesDetail(
    habitat: "Vive in boschi di latifoglie e conifere alternati a radure, prati e pascoli montani. Il bosco offre riparo, mentre gli spazi aperti permettono di alimentarsi. Frequenta anche i margini fra foresta e prateria; lungo i sentieri osserva a distanza le radure nelle ore tranquille.",
    seasonLevels: [2, 2, 4, 1],
    asset: "cervo",
    size: "180–250 cm",
    mass: "120–250 kg",
    activity: "Alba e tramonto",
    tags: ["Foreste", "Aree montane", "Radure e pascoli"],
    signs: [
      ("Impronta", "Zoccolo ovale con due unghioni; leggi anche la pista."),
      ("Fatte", "Pellet scuri raggruppati; forma variabile con la dieta."),
      ("Sfregamenti", "Corteccia consumata dai palchi su giovani tronchi."),
      (
        "Palchi",
        "Ramificati e rinnovati ogni anno; lascia i reperti sul posto.",
      ),
    ],
    seasons: ["Radure", "Ore fresche", "Bramito", "Piste sulla neve"],
    photo: "Inquadra il cervo da un punto riparato, con teleobiettivo e senza avvicinarti al branco.",
    source: "https://www.parcoabruzzo.it/fauna.schede.dettaglio.php?id=313",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Capriolo": SpeciesDetail(
    habitat: "Predilige boschi con sottobosco ricco, margini forestali e piccole radure, spesso in mosaico con prati e coltivi. Gli arbusti offrono rifugio e germogli di cui nutrirsi. È presente dal fondovalle agli ambienti montani; osserva i margini senza entrare nelle zone di riposo o cercare i piccoli.",
    seasonLevels: [3, 3, 2, 2],
    asset: "capriolo",
    size: "90–130 cm",
    mass: "10–27 kg",
    activity: "Radure nelle ore tranquille",
    tags: ["Margini boschivi", "Radure", "Campagne"],
    signs: [
      (
        "Impronta",
        "Piccoli unghioni appuntiti; confronta la pista con il cervo.",
      ),
      (
        "Fatte",
        "Piccoli pellet scuri; il solo aspetto non basta a identificarli.",
      ),
      ("Sfregamenti", "Segni sui giovani fusti; valuta altezza e contesto."),
      ("Palchi", "Corti, spesso con tre punte nei maschi adulti."),
    ],
    seasons: ["Radure", "Amori estivi", "Margini boschivi", "Manto grigio"],
    photo: "Aspetta ai margini del bosco e fotografa senza entrare nelle aree dove i piccoli riposano.",
    source: "https://www.areeprotettealpimarittime.it/fauna/capriolo",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Volpe": SpeciesDetail(
    habitat: "Occupa ambienti molto diversi: boschi, prati, campagne e margini degli abitati. Cerca territori dove trovare cibo e copertura, con vegetazione fitta o terreni adatti alle tane. L’alternanza fra aree aperte e rifugi favorisce la sua presenza; una singola osservazione non indica che l’animale sia abituato alle persone.",
    seasonLevels: [2, 2, 2, 2],
    asset: "volpe",
    size: "60–80 cm",
    mass: "6–10 kg",
    activity: "Soprattutto crepuscolo e notte",
    tags: ["Boschi", "Campagne", "Periferie"],
    signs: [
      (
        "Impronta",
        "Quattro dita con unghie: è simile a quella di altri canidi.",
      ),
      (
        "Fatte",
        "Possono contenere peli o semi; evita attribuzioni da un solo reperto.",
      ),
      (
        "Tane",
        "Ingressi nel terreno; osserva senza avvicinarti né appostarti davanti.",
      ),
      (
        "Peli",
        "Pelo rossastro e coda folta sono indizi da associare a foto e pista.",
      ),
    ],
    seasons: ["Margini", "Ore fresche", "Frutti e bacche", "Piste sulla neve"],
    photo: "Fotografa a distanza con tempi rapidi; non attirare la volpe con cibo e non inseguirla.",
    source: "https://www.parcoabruzzo.it/fauna.schede.dettaglio.php?id=314",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Camoscio alpino": SpeciesDetail(
    habitat: "Frequenta versanti montani ripidi, praterie alpine, ghiaioni e zone rocciose, ma anche boschi e radure alle quote inferiori. Le pareti vicine offrono vie di fuga e riparo. La distribuzione cambia con innevamento e disponibilità di vegetazione; osserva dai sentieri, evitando di tagliare le vie di passaggio.",
    seasonLevels: [2, 3, 3, 1],
    asset: "camoscio",
    size: "100–130 cm",
    mass: "70–90 cm al garrese",
    activity: "Versanti aperti, senza disturbo",
    tags: ["Rocce", "Pascoli alpini", "Boschi ripidi"],
    signs: [
      (
        "Impronta",
        "Due unghioni; forma e dimensioni cambiano con terreno e passo.",
      ),
      (
        "Fatte",
        "Pellet da ungulato: senza altri indizi non distinguono la specie.",
      ),
      (
        "Passaggi",
        "Piste su pendii e cenge; non seguire gli animali fuori sentiero.",
      ),
      ("Corna", "Sottili e uncinate; permanenti, non palchi caduti ogni anno."),
    ],
    seasons: ["Versanti", "Alta quota", "Amori", "Risparmio energia"],
    photo: "Usa un teleobiettivo dal sentiero e lascia libera la via di fuga, soprattutto con neve.",
    source: "https://www.pngp.it/fr/node/3559",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Stambecco": SpeciesDetail(
    habitat: "È legato alle praterie alpine e ai pendii rocciosi sopra il limite del bosco, con cenge e pareti scoscese usate come rifugio. Si alimenta negli spazi erbosi vicini alle rocce. Innevamento ed esposizione dei versanti influenzano gli spostamenti stagionali; mantieni libera la strada verso le pareti.",
    seasonLevels: [2, 3, 3, 1],
    asset: "stambecco",
    size: "Circa 160 cm ♂",
    mass: "Circa 90 kg ♂",
    activity: "Pendii rocciosi e pascoli",
    tags: ["Rocce", "Praterie alpine", "Alta quota"],
    signs: [
      (
        "Impronta",
        "Due unghioni da caprino; leggi l’intera pista su neve o terra.",
      ),
      ("Fatte", "Pellet scuri nei pascoli; il solo reperto non è diagnostico."),
      ("Corna", "Nei maschi sono grandi, arcuate e con rilievi anteriori."),
      (
        "Passaggi",
        "Cenge e rocce frequentate; lascia sempre libero il percorso.",
      ),
    ],
    seasons: ["Pascoli", "Alta quota", "Versanti", "Amori"],
    photo: "Cura sfondo e profilo delle corna; resta lontano anche quando lo stambecco sembra confidente.",
    source: "https://www.pngp.it/natura-e-ricerca/fauna/praterie-e-ambienti-rocciosi/lo-stambecco",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Cinghiale": SpeciesDetail(
    habitat: "Vive in boschi, macchia e mosaici di vegetazione naturale e terreni agricoli. La copertura fitta offre riparo, mentre il terreno soffice e gli spazi aperti forniscono alimenti. Può frequentare margini e corsi d’acqua; resta sui percorsi e non entrare nel sottobosco per cercare gli animali.",
    seasonLevels: [1, 1, 2, 1],
    asset: "cinghiale",
    size: "100–150 cm",
    mass: "Corpo robusto",
    activity: "Notte e crepuscolo",
    tags: ["Boschi", "Macchia", "Campagne"],
    signs: [
      (
        "Impronta",
        "Due unghioni; nel fango possono apparire anche gli speroni.",
      ),
      (
        "Fatte",
        "Aspetto variabile con dieta e stagione: considera altri segni.",
      ),
      ("Grufolate", "Suolo rivoltato dal grugno durante la ricerca di cibo."),
      (
        "Insogli",
        "Pozze di fango usate per bagnarsi; possibili sfregamenti vicini.",
      ),
    ],
    seasons: ["Boschi", "Pozze di fango", "Ghiande", "Piste"],
    photo: "Fotografa da lontano, senza avvicinarti ai piccoli né bloccare una via di fuga.",
    source: "https://www.gransassolagapark.it/pagina.php?id=261",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Aquila reale": SpeciesDetail(
    habitat: "Frequenta montagne con praterie, creste e versanti aperti per la caccia, associati a pareti rocciose adatte alla nidificazione. Usa territori molto estesi e correnti ascensionali per spostarsi. Cerca il volo sopra valloni e crinali dai punti panoramici autorizzati, senza avvicinarti alle pareti occupate dai nidi.",
    seasonLevels: [2, 3, 2, 2],
    asset: "aquila",
    size: "76–93 cm",
    mass: "3–6,6 kg",
    activity: "Volo planato sulle correnti",
    tags: ["Pareti rocciose", "Praterie", "Montagna"],
    signs: [
      (
        "Impronta",
        "Dita con artigli da rapace; lo schema non identifica la specie da solo.",
      ),
      (
        "Penne",
        "Grandi remiganti: una penna isolata richiede verifica esperta.",
      ),
      ("Posatoi", "Rocce dominanti utilizzate come punti di osservazione."),
      ("Giovani", "Bianco su ali e coda nei giovani; varia con l’età."),
    ],
    seasons: ["Territorio", "Volo planato", "Dispersione", "Presente"],
    photo: "Segui la silhouette con autofocus continuo e tempi rapidi; non cercare né fotografare il nido da vicino.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/aquila-reale",
    badge: "NT",
    status: "Quasi minacciata · Italia",
    note: "",
  ),
  "Grifone": SpeciesDetail(
    habitat: "Ha bisogno di pareti rocciose con cenge per nidificare e riposare, vicine ad ampi spazi aperti dove cercare carcasse. Può sorvolare pascoli, vallate e rilievi a grandi distanze dalla colonia. Le correnti ascensionali favoriscono il volo; usa i punti di osservazione autorizzati e non cercare i nidi.",
    seasonLevels: [3, 3, 2, 2],
    asset: "grifone",
    size: "Circa 100 cm",
    mass: "7,3–11,2 kg",
    activity: "Volo sulle correnti ascensionali",
    tags: ["Falesie", "Spazi aperti", "Prealpi"],
    signs: [
      (
        "Impronta",
        "Dita con artigli da rapace; lo schema non identifica la specie da solo.",
      ),
      ("Penne", "Remiganti grandi e scure; non attribuirle senza confronto."),
      ("Colonie", "Gruppi sulle pareti; osserva dai punti autorizzati."),
      (
        "Alimentazione",
        "Consuma carcasse: non avvicinarti ai punti di alimentazione.",
      ),
    ],
    seasons: ["Termiche", "Volo planato", "Gruppi", "Presente"],
    photo: "Usa il cielo o le pareti come sfondo e fotografa dai punti consentiti senza disturbare la colonia.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/grifone",
    badge: "NT",
    status: "Cattivo · Italia",
    note: "",
  ),
  "Poiana": SpeciesDetail(
    habitat: "Predilige paesaggi con boschi e piccoli gruppi di alberi alternati a prati, pascoli e coltivi. Gli alberi offrono siti di nidificazione e posatoi, mentre le aree aperte sono usate per cacciare. Può frequentare pianure, colline e montagne; osserva da punti sicuri, senza fermarti sulle carreggiate.",
    seasonLevels: [3, 3, 3, 3],
    asset: "poiana",
    size: "51–57 cm",
    mass: "0,5–1,4 kg",
    activity: "Posatoi e volo diurno",
    tags: ["Campagne", "Colline", "Margini forestali"],
    signs: [
      (
        "Impronta",
        "Dita con artigli da rapace; lo schema non identifica la specie da solo.",
      ),
      ("Penne", "Penne barrate: confronta misura e disegno con altre specie."),
      ("Posatoi", "Alberi, pali e margini dei campi utilizzati per cacciare."),
      (
        "Richiamo",
        "Richiamo acuto e lamentoso; confrontalo con l’audio verificato.",
      ),
    ],
    seasons: ["Territori", "Volo", "Passaggi", "Svernanti"],
    photo: "Fotografa da un luogo sicuro ai margini dei campi; non sostare sulla carreggiata per seguire un posatoio.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/poiana",
    badge: "LC",
    status: "Favorevole · Italia",
    note: "",
  ),
  "Allocco": SpeciesDetail(
    habitat: "È legato ad ambienti alberati: boschi maturi, parchi e paesaggi rurali con grandi alberi. Le cavità dei tronchi possono ospitare il nido e rifugi diurni, mentre bosco e radure offrono prede. È prevalentemente notturno: spesso il richiamo rivela la presenza prima di un’osservazione diretta.",
    seasonLevels: [1, 1, 1, 1],
    asset: "allocco",
    size: "37–43 cm",
    mass: "81–96 cm apertura",
    activity: "Prevalentemente notturno",
    tags: ["Boschi maturi", "Parchi", "Cavità arboree"],
    signs: [
      (
        "Borre",
        "Rigurgiti con ossa e peli non digeriti, da verificare sul posto.",
      ),
      ("Penne", "Piumaggio bruno o grigio; non identifica da solo la specie."),
      ("Cavità", "Usa cavità degli alberi; non ispezionare il rifugio."),
      ("Capo", "Testa rotonda, occhi scuri e assenza di ciuffi auricolari."),
    ],
    seasons: ["Richiami", "Bosco", "Territorio", "Presente"],
    photo: "Sfrutta la luce naturale residua e alza gli ISO; evita flash, torce puntate e richiami riprodotti.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/allocco",
    badge: "LC",
    status: "Minor preoccupazione · Italia",
    note: "",
  ),
  "Picchio nero": SpeciesDetail(
    habitat: "Frequenta boschi maturi di conifere e latifoglie con alberi di grandi dimensioni, tronchi con cavità e legno morto. Questi elementi offrono siti di nidificazione e insetti di cui nutrirsi. È soprattutto legato agli ambienti forestali: ascolta i richiami e osserva i tronchi dai sentieri, senza cercare il nido.",
    seasonLevels: [3, 2, 2, 2],
    asset: "picchio",
    size: "45–47 cm",
    mass: "255–315 g",
    activity: "Richiami e tambureggiamento",
    tags: ["Boschi maturi", "Legno morto", "Faggete"],
    signs: [
      (
        "Scavi",
        "Cavità e scavi nel legno; più specie possono usare lo stesso albero.",
      ),
      ("Trucioli", "Legno appena staccato vicino agli scavi alimentari."),
      ("Penne", "Nere; associa il reperto all’osservazione del capo rosso."),
      (
        "Tamburo",
        "Tambureggiamento sui tronchi; distinto dal richiamo in volo.",
      ),
    ],
    seasons: ["Tamburo", "Bosco", "Presente", "Presente"],
    photo: "Attendi su un sentiero e usa tempi rapidi per il movimento; evita di sostare davanti alle cavità.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/picchio-nero",
    badge: "LC",
    status: "Inadeguato · Italia",
    note: "",
  ),
  "Airone cenerino": SpeciesDetail(
    habitat: "Frequenta fiumi, laghi, paludi, canali e altre zone umide con acque poco profonde, dove cerca pesci e altre prede. Può alimentarsi anche nei campi e nei prati. Nidifica spesso in colonie su alberi vicini alle aree di alimentazione; osserva dalle rive accessibili o dagli osservatori.",
    seasonLevels: [3, 3, 3, 3],
    asset: "airone",
    size: "90–98 cm",
    mass: "1–2 kg",
    activity: "Caccia in acqua bassa",
    tags: ["Zone umide", "Fiumi", "Lagune"],
    signs: [
      (
        "Impronta",
        "Dita lunghe nel fango delle sponde; confronta le dimensioni.",
      ),
      (
        "Penne",
        "Grigie e bianche; la sola penna non distingue tutti gli aironi.",
      ),
      ("Caccia", "Resta immobile o avanza lentamente cercando prede."),
      ("Volo", "Collo ripiegato e zampe protratte dietro il corpo."),
    ],
    seasons: ["Zone umide", "Acque basse", "Passaggi", "Svernanti"],
    photo: "Fotografa dai capanni all’altezza dell’acqua; anticipa lo scatto quando il becco punta verso la preda.",
    source:
        "https://www.lipu.it/uccelli/conoscerli-proteggerli/airone-cenerino",
    badge: "LC",
    status: "Inadeguato · Italia",
    note: "",
  ),
  "Germano reale": SpeciesDetail(
    habitat: "Occupa laghi, stagni, fiumi lenti e paludi, ma anche bacini e canali in paesaggi agricoli o urbani. Preferisce zone con vegetazione ripariale e tratti di acqua bassa per alimentarsi. La copertura sulle sponde offre riparo e siti di nidificazione; osserva a distanza senza nutrire gli uccelli.",
    seasonLevels: [3, 3, 3, 3],
    asset: "germano",
    size: "50–65 cm",
    mass: "600–1.490 g",
    activity: "Acque basse e superficie",
    tags: ["Laghi", "Fiumi", "Paludi"],
    signs: [
      ("Impronta", "Piede palmato: altre anatre possono lasciare orme simili."),
      (
        "Penne",
        "Specchio alare blu-violetto; controlla anche gli altri caratteri.",
      ),
      (
        "Maschio",
        "Testa verde nel piumaggio riproduttivo; l’aspetto cambia con la muta.",
      ),
      (
        "Femmina",
        "Bruna screziata; distinguila da altre anatre con più dettagli.",
      ),
    ],
    seasons: ["Coppie", "Muta", "Gruppi", "Svernanti"],
    photo: "Abbassa il punto di ripresa senza uscire dal percorso e non usare pane per avvicinare le anatre.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/germano-reale",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Falco di palude": SpeciesDetail(
    habitat: "È legato alle zone umide con canneti estesi, paludi e vegetazione emergente, usati anche per nidificare. Caccia volando basso sopra canneti, prati e campi vicini. Le aree umide dell’Alto Adriatico sono importanti per la specie; osserva dagli argini consentiti senza entrare nei canneti.",
    seasonLevels: [3, 3, 2, 2],
    asset: "falco",
    size: "48–56 cm",
    mass: "485–800 g",
    activity: "Volo basso sui canneti",
    tags: ["Canneti", "Paludi", "Zone umide"],
    signs: [
      (
        "Sagoma",
        "Ali lunghe, spesso tenute rialzate durante il volo di caccia.",
      ),
      ("Piumaggio", "Diverso per sesso ed età; documenta capo, ali e coda."),
      ("Caccia", "Perlustra i canneti con volo lento vicino alla vegetazione."),
      ("Penne", "Confronta disegno e misure: non basta un reperto isolato."),
    ],
    seasons: ["Passaggi", "Canneti", "Migrazione", "Svernanti"],
    photo: "Segui il volo con autofocus continuo dal capanno; lascia integri i canneti e non cercare i nidi.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/falco-palude",
    badge: "LC",
    status: "Favorevole · Italia",
    note: "",
  ),
  "Orso bruno": SpeciesDetail(
    habitat: "Frequenta paesaggi montani con grandi boschi, radure e pascoli, dove trovare cibo e aree tranquille. Usa territori ampi e si sposta fra ambienti diversi secondo le risorse stagionali. La copertura forestale e la continuità degli habitat sono importanti; la presenza non implica che sia facile o opportuno avvicinarlo.",
    seasonLevels: [1, 1, 1, 1],
    asset: "orso",
    size: "150–180 cm ♂*",
    mass: "140–210 kg ♂*",
    activity: "Osservazione a grande distanza",
    tags: ["Boschi montani", "Radure", "Appennino e Alpi"],
    signs: [
      (
        "Impronta",
        "Cinque dita; osserva la pista senza seguirla verso l’animale.",
      ),
      (
        "Pietre",
        "Può rivoltare pietre per cercare insetti; non è un segno esclusivo.",
      ),
      ("Fatte", "Contenuto variabile con frutti, insetti e altri alimenti."),
      ("Peli", "Peli su vegetazione o passaggi: documenta senza raccogliere."),
    ],
    seasons: ["Distanza", "Alimentazione", "Frutti", "Riposo"],
    photo: "Usa un lungo teleobiettivo dai punti autorizzati: non cercare di ridurre la distanza e non lasciare cibo.",
    source: "https://www.parcoabruzzo.it/scheda-orso.php",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "*Maschio di orso marsicano: dati riferiti alla popolazione appenninica, non a tutte le popolazioni di orso bruno.",
  ),
  "Lupo": SpeciesDetail(
    habitat: "È adattabile e può utilizzare boschi, praterie e paesaggi montani a quote diverse. Ha bisogno di territori ampi con prede, rifugi e possibilità di spostamento fra aree adatte. Durante il giorno può restare nelle zone più tranquille; impronte e altri indizi sono spesso più facili da trovare dell’animale.",
    seasonLevels: [1, 1, 1, 1],
    asset: "lupo",
    size: "110–148 cm",
    mass: "25–40 kg",
    activity: "Elusivo; avvistamenti rari",
    tags: ["Boschi", "Praterie", "Montagna"],
    signs: [
      (
        "Impronta",
        "Simile a un grosso cane; serve anche la sequenza della pista.",
      ),
      (
        "Fatte",
        "Possono contenere peli; evita di toccarle o identificarle da sole.",
      ),
      (
        "Pista",
        "Orme spesso allineate; la regolarità non è una prova definitiva.",
      ),
      (
        "Ululato",
        "Richiamo sociale: non usare l’audio per provocare risposte.",
      ),
    ],
    seasons: ["Elusivo", "Elusivo", "Elusivo", "Piste sulla neve"],
    photo: "Documenta più caratteri con il teleobiettivo; non inseguire, attirare o confondere un cane con un lupo.",
    source: "https://www.parcoabruzzo.it/fauna.schede.dettaglio.php?id=21",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Sciacallo dorato": SpeciesDetail(
    habitat: "Frequenta mosaici di ambienti aperti e vegetazione di copertura, come campagne, arbusteti e margini boschivi. Le zone riparate permettono di riposare, mentre gli spazi aperti offrono alimenti. La presenza nel Nord-Est è oggetto di monitoraggio: non dedurla dal solo paesaggio e documenta gli indizi senza disturbare.",
    seasonLevels: [1, 1, 1, 1],
    asset: "sciacallo",
    size: "70–85 cm ♂",
    mass: "6–14 kg ♂",
    activity: "Documenta luogo e ora",
    tags: ["Campagne", "Boschi radi", "Nord-est"],
    signs: [
      ("Impronta", "Orma da canide, simile a volpe e cane: da sola non basta."),
      (
        "Mantello",
        "Mantello fulvo con sfumature grigie: valuta anche proporzioni.",
      ),
      ("Sagoma", "Muso affusolato e corporatura da canide medio."),
      (
        "Richiamo",
        "Vocalizzazioni da confrontare con registrazioni affidabili.",
      ),
    ],
    seasons: [
      "Presenza locale",
      "Presenza locale",
      "Presenza locale",
      "Presenza locale",
    ],
    photo: "Fotografa senza avvicinarti e annota luogo, ora e caratteri visibili; non attirarlo con cibo o audio.",
    source: "https://www.mabalpiledrensijudicaria.tn.it/dettaglio.php?id=62794",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Marmotta": SpeciesDetail(
    habitat: "Vive nelle praterie alpine e nei pascoli montani aperti, spesso vicini a pietraie e pendii con suolo adatto a scavare tane. Si nutre della vegetazione erbacea e usa i rifugi sotterranei anche per il letargo. Osserva nelle stagioni senza neve, restando lontano dagli ingressi delle tane.",
    seasonLevels: [2, 4, 2, 0],
    asset: "marmotta",
    size: "50–60 cm",
    mass: "3–6 kg",
    activity: "Praterie alpine, di giorno",
    tags: ["Praterie alpine", "Tane", "Pascoli"],
    signs: [
      ("Tane", "Ingressi nel terreno; non ostruirli né appostarti davanti."),
      ("Impronta", "Pista da roditore; terreno e passo modificano il disegno."),
      ("Fischio", "Segnale d’allarme: fermati e aumenta la distanza."),
      ("Alimentazione", "Erbe e germogli nei pascoli intorno alle tane."),
    ],
    seasons: ["Risveglio", "Attiva", "Verso il letargo", "Letargo"],
    photo: "Riprendi da lontano all’altezza dell’animale e interrompi l’avvicinamento quando emette fischi d’allarme.",
    source: "https://ambiente.regione.emilia-romagna.it/it/parchi-natura2000/sistema-regionale/fauna/mammiferi/schede/marmotta",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Ermellino": SpeciesDetail(
    habitat: "Frequenta prati, pascoli montani, pietraie e margini di ambienti boschivi. Piccoli anfratti, muretti e vegetazione bassa offrono copertura mentre cerca piccoli mammiferi. Può muoversi rapidamente fra rifugi vicini ed è difficile da osservare; una pista sulla neve va interpretata insieme ad altri elementi.",
    seasonLevels: [1, 1, 1, 1],
    asset: "ermellino",
    size: "24–29 cm",
    mass: "125–450 g",
    activity: "Rapido ed elusivo",
    tags: ["Rocce", "Pascoli", "Ambienti alpini"],
    signs: [
      ("Impronta", "Piccole orme da mustelide; verifica l’intera pista."),
      ("Coda", "Punta nera anche nel mantello invernale bianco."),
      ("Mantello", "Dorso bruno e ventre chiaro in estate; bianco in inverno."),
      ("Rifugi", "Anfratti e pietre: osserva senza smuovere né esplorare."),
    ],
    seasons: ["Cambio manto", "Manto bruno", "Cambio manto", "Manto bianco"],
    photo: "Prepara autofocus continuo e tempi rapidi; fotografa la punta della coda e non smuovere le pietre.",
    source: "https://www.pngp.it/natura-e-ricerca/fauna/carnivori/l-ermellino",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "",
  ),
  "Tasso": SpeciesDetail(
    habitat: "Predilige mosaici di boschi, siepi, prati e coltivi con copertura e disponibilità di alimenti. Il terreno adatto allo scavo permette di realizzare tane e sistemi di gallerie usati come rifugio. È soprattutto attivo nelle ore notturne: osserva gli indizi lungo i percorsi senza avvicinarti alle tane.",
    seasonLevels: [1, 1, 1, 1],
    asset: "tasso",
    size: "Fino a circa 1 m*",
    mass: "Fino a 17 kg",
    activity: "Osserva senza sostare alle tane",
    tags: ["Boschi", "Coltivi", "Praterie"],
    signs: [
      (
        "Impronta",
        "Cinque dita e unghie; la pista aiuta a distinguere i mustelidi.",
      ),
      (
        "Tane",
        "Più ingressi e terra smossa: non entrare né bloccare i passaggi.",
      ),
      ("Muso", "Bande nere longitudinali sul fondo chiaro."),
      (
        "Piste",
        "Passaggi nella vegetazione; non creare appostamenti davanti alle tane.",
      ),
    ],
    seasons: ["Boschi", "Ore tranquille", "Boschi", "Presenza locale"],
    photo: "Sfrutta la luce naturale disponibile da lontano; evita flash e non presidiare gli ingressi delle tane.",
    source: "https://www.parchilazio.it/schede-32368-tasso_rimesso_in_natura_dai_guardiaparco",
    badge: null,
    status: "Consulta la valutazione nella fonte",
    note: "*Lunghezza comprensiva della coda.",
  ),
  "Gracchio alpino": SpeciesDetail(
    habitat: "È legato alle montagne con pareti, cavità rocciose e praterie alpine. Usa le rocce per riposare e nidificare, mentre cerca cibo negli spazi aperti; può frequentare anche aree vicine ai rifugi. Gli spostamenti seguono la disponibilità di alimenti e le condizioni stagionali; non attirarlo con avanzi.",
    seasonLevels: [2, 3, 3, 2],
    asset: "gracchio",
    size: "38 cm",
    mass: "168–246 g",
    activity: "Gruppi e volo in montagna",
    tags: ["Rocce", "Praterie alpine", "Alta quota"],
    signs: [
      (
        "Impronta",
        "Tre dita avanti e una dietro; la sola orma non distingue i corvidi.",
      ),
      ("Zampe", "Rosse negli adulti; controlla anche becco e sagoma."),
      ("Penne", "Nere; non distinguono da sole i corvidi."),
      ("Gruppi", "Volo sociale presso pareti e praterie di montagna."),
    ],
    seasons: ["Montagna", "Insetti", "Bacche", "Spostamenti"],
    photo: "Segui il volo con tempi rapidi e documenta il becco; non offrire cibo vicino a rifugi e sentieri.",
    source:
        "https://www.lipu.it/uccelli/conoscerli-proteggerli/gracchio-alpino",
    badge: "LC",
    status: "Inadeguato · Italia",
    note: "",
  ),
  "Gufo reale": SpeciesDetail(
    habitat: "Frequenta vallate con pareti rocciose, boschi e spazi aperti dove cacciare. Le cenge e gli anfratti delle rocce possono ospitare il nido e rifugi diurni. È un rapace prevalentemente notturno: osserva da lontano senza cercare il nido, usare flash o riprodurre richiami.",
    seasonLevels: [1, 1, 1, 1],
    asset: "gufo",
    size: "60–75 cm",
    mass: "1,5–2,5 kg",
    activity: "Sera e notte, senza richiami",
    tags: ["Pareti rocciose", "Vallate", "Spazi aperti"],
    signs: [
      (
        "Impronta",
        "Piede con artigli; il dito esterno può ruotare indietro. Verifica anche gli altri segni.",
      ),
      (
        "Borre",
        "Rigurgiti con resti non digeriti: più rapaci producono borre.",
      ),
      ("Penne", "Mottate e barrate; non avvicinarti ai siti di riposo."),
      (
        "Richiamo",
        "Vocalizzazione territoriale profonda; non provocare risposte.",
      ),
    ],
    seasons: ["Territorio", "Distanza", "Territorio", "Presente"],
    photo: "Fotografa solo da lontano con luce naturale; evita flash e qualsiasi avvicinamento ai siti riproduttivi.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/gufo-reale",
    badge: "NT",
    status: "Quasi minacciata · Italia",
    note: "",
  ),
  "Barbagianni": SpeciesDetail(
    habitat: "Vive soprattutto in paesaggi aperti di pianura e collina con prati, coltivi, siepi e piccoli insediamenti. Gli spazi aperti permettono di cacciare piccoli mammiferi; cavità e vecchi edifici possono offrire rifugio e siti di nidificazione. È notturno: osserva a distanza e non entrare nei luoghi di riposo.",
    seasonLevels: [1, 1, 1, 1],
    asset: "barbagianni",
    size: "33–35 cm",
    mass: "85–93 cm apertura",
    activity: "Notte nei paesaggi rurali",
    tags: ["Campagne", "Edifici rurali", "Cavità"],
    signs: [
      (
        "Impronta",
        "Piede con artigli; il dito esterno può ruotare indietro. Verifica anche gli altri segni.",
      ),
      (
        "Borre",
        "Resti di prede rigurgitati: documenta senza entrare nei rifugi.",
      ),
      ("Penne", "Piumaggio chiaro con dorso dorato; confronta più caratteri."),
      (
        "Stridio",
        "Vocalizzazione stridente, diversa dall’ululato di altri gufi.",
      ),
    ],
    seasons: ["Campagne", "Campagne", "Campagne", "Presenza locale"],
    photo: "Usa luce naturale residua e ISO elevati; osserva dall’esterno e non entrare negli edifici occupati.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/barbagianni",
    badge: "LC",
    status: "Cattivo · Italia",
    note: "",
  ),
  "Ghiandaia": SpeciesDetail(
    habitat: "Frequenta boschi di latifoglie e misti, margini forestali e parchi alberati. Gli alberi offrono copertura e siti di nidificazione, mentre ghiande, semi e altri alimenti sostengono la dieta. Tra estate e autunno raccoglie e nasconde molte ghiande; ascolta i richiami e osserva senza inseguirla.",
    seasonLevels: [2, 2, 3, 2],
    asset: "ghiandaia",
    size: "34–35 cm",
    mass: "125–205 g",
    activity: "Boschi e ambienti alberati",
    tags: ["Boschi", "Querceti", "Parchi"],
    signs: [
      (
        "Impronta",
        "Tre dita avanti e una dietro; la sola orma non distingue i corvidi.",
      ),
      ("Penne", "Le piccole penne azzurre sono un indizio da verificare."),
      ("Capo", "Documenta disegno del capo e area scura vicino al becco."),
      (
        "Richiami",
        "Vocalizzazioni forti e varie, ascoltabili nella sezione Versi.",
      ),
    ],
    seasons: ["Boschi", "Boschi", "Boschi", "Boschi"],
    photo: "Attendi in silenzio e riprendi il pannello azzurro dell’ala; evita di inseguirla fra gli alberi.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/ghiandaia",
    badge: "LC",
    status: "Favorevole · Italia",
    note: "",
  ),
"Lepre": SpeciesDetail(
    habitat: "Frequenta prati, campi coltivati e margini erbosi dove alternare alimentazione e riposo. Siepi e fasce incolte offrono copertura; i campi aperti permettono di individuare il pericolo. Riposa in una depressione superficiale chiamata covo, non in una tana scavata come il coniglio. Presenza e densità variano localmente.",
    asset: "lepre",
    size: "Corpo 48–70 cm",
    mass: "Circa 2,5–6,5 kg",
    activity: "Alba, tramonto e notte",
    photo: "AF-C sull'occhio, tempo iniziale 1/1000 s; 1/2000 s per la corsa. Attendi da un margine senza attraversare il campo.",
    source: "https://www.woodlandtrust.org.uk/blog/2023/03/why-do-hares-box/",
    bestPeriod: "Per la fotografia privilegia alba e tramonto, soprattutto nei campi con vegetazione bassa in primavera. È attiva anche di notte, quando l'osservabilità visiva cala.",
    diet: "Erbe e altre parti vegetali; la composizione cambia con la stagione.",
    breeding: "Più parti durante la stagione riproduttiva; i leprotti riposano separati dalla madre e non vanno raccolti.",
    voiceDescription: "Generalmente silenziosa; vocalizzazioni acute possono accompagnare forte stress. Non provocarle.",
    tags: ["Prati", "Campagne", "Siepi"], seasons: ["Mar–Mag: campi bassi, alba e tramonto; osserva le interazioni senza avvicinarti.", "Giu–Ago: ore fresche e margini; la vegetazione alta limita la visibilità.", "Set–Nov: prati e coltivi nelle ultime ore di luce; considera lavori agricoli e disturbo.", "Dic–Feb: piste su neve dove presente; usa riparo e distanza."], seasonLevels: [4, 2, 3, 2],
    newArtwork: true,
    signs: [("Impronta","Zampe posteriori lunghe davanti alle anteriori nella sequenza dei balzi; confronta più orme."),("Fatte","Pellet tondeggianti con fibre vegetali. Dimensioni e colore variano; non sono diagnostici da soli."),("Covo","Depressione fra erba o terra dove riposa. Osserva senza cercare di farla uscire."),("Orecchie","Lunghe con estremità nera; identifica insieme a corporatura e coda.")],
  ),
"Scoiattolo": SpeciesDetail(
    habitat: "Vive fra alberi che offrono semi, rifugi e collegamenti fra le chiome. Frequenta boschi di conifere, latifoglie, boschi misti e parchi con vegetazione continua. Scende a terra per alimentarsi e nascondere cibo. Il colore del pelo non basta a distinguerlo da specie introdotte o dallo scoiattolo meridionale.",
    asset: "scoiattolo",
    size: "Corpo 18–24 cm · coda 14–20 cm",
    mass: "Circa 250–350 g",
    activity: "Diurno, soprattutto mattino",
    photo: "AF-C e raffica breve, 1/1000 s come partenza; trova uno sfondo distante. Non usare nocciole come esca.",
    source: "https://www.woodlandtrust.org.uk/trees-woods-and-wildlife/animals/mammals/red-squirrel/",
    bestPeriod: "Mattino e secondo pomeriggio nei boschi frequentati; l'autunno permette di osservare la raccolta di semi. In inverno non è in letargo, ma il maltempo riduce l'attività.",
    diet: "Semi, frutti a guscio, gemme e funghi; la dieta segue le risorse del bosco.",
    breeding: "Nidi di rami e foglie, o cavità; può avere più di una cucciolata nell'anno. Mantieni distanza dai nidi.",
    voiceDescription: "Richiami brevi e scatti vocali possono segnalare allarme; ascolta senza sollecitarli.",
    tags: ["Boschi misti", "Conifere", "Parchi"], seasons: ["Mar–Mag: mattino nei boschi; attenzione ai nidi e alla riproduzione.", "Giu–Ago: ore fresche, spesso nascosto dal fogliame; attendi sui percorsi abituali.", "Set–Nov: raccolta e accumulo di semi; buona stagione per osservare comportamenti.", "Dic–Feb: resta attivo, con pause per il maltempo; più visibile nei boschi spogli."], seasonLevels: [3, 2, 4, 3],
    newArtwork: true,
    signs: [("Impronta","Piccole orme anteriori e posteriori con dita e unghie; documenta la sequenza dei balzi."),("Fatte","Piccoli elementi allungati; considera anche rosicchiature e contesto."),("Pigne","Pigne consumate con asse centrale esposto e squame staccate; confronta con segni di altri roditori."),("Nido","Globo di rametti e foglie fra i rami; non cercare di aprirlo o avvicinarti.")],
  ),
"Upupa": SpeciesDetail(
    habitat: "Preferisce mosaici aperti e soleggiati con suolo accessibile e alberi o manufatti che offrano cavità. Prati corti, frutteti e filari permettono di cercare invertebrati sondando il terreno. In Italia è soprattutto migratrice e nidificante nella bella stagione; eventuali presenze invernali non giustificano suggerimenti generalizzati.",
    asset: "upupa",
    size: "25–29 cm · ali 44–48 cm",
    mass: "Circa 50–90 g",
    activity: "Diurna, sui terreni aperti",
    photo: "1/1000 s, AF-C; scatta dal margine con sfondo basso e non seguire i voli al nido.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/upupa",
    bestPeriod: "Soprattutto aprile–agosto; mattino nei prati corti per fotografia e ascolto. Marzo e settembre dipendono dalla migrazione locale.",
    diet: "Insetti e larve cercati nel terreno, con altri piccoli invertebrati.",
    breeding: "Depone in cavità di alberi, rocce o manufatti; entrambi i genitori alimentano i piccoli.",
    voiceDescription: "Serie di note morbide e ripetute, simili a 'up-up-up'. Ascolto passivo.",
    tags: ["Prati corti", "Frutteti", "Filari"], seasons: ["Mar–Mag: ritorno migratorio e canto; mattino nei prati e frutteti.", "Giu–Ago: alimentazione e giovani; evita i siti di nidificazione.", "Set–Nov: partenze migratorie, soprattutto inizio autunno; presenza in calo.", "Dic–Feb: in genere assente; rare presenze locali vanno documentate."], seasonLevels: [4, 3, 1, 0],
    newArtwork: true,
    signs: [("Impronta","Tre dita avanti e una dietro; le piccole orme da sole non identificano l'upupa."),("Fatte","Deiezioni con urati chiari; non usarle per identificare la specie."),("Penne","Bande bianche e nere: confronta forma e contesto, lascia i reperti sul posto."),("Alimentazione","Becco lungo che sonda il terreno; osserva da un margine senza inseguirla.")],
  ),
"Gheppio": SpeciesDetail(
    habitat: "Frequenta ambienti aperti e semiaperti dove individuare le prede, con posatoi o cavità per riposare e nidificare. Si trova in campagne, pascoli, versanti rocciosi e città con spazi erbosi. La presenza di terreni adatti è più utile della sola vicinanza a una parete o a un edificio.",
    asset: "gheppio",
    size: "30–34 cm · ali 60–75 cm",
    mass: "115–280 g",
    activity: "Diurno, spesso in spirito santo",
    photo: "Per lo spirito santo parti da 1/2000 s, AF-C e area ampia; usa raffiche brevi.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/gheppio",
    bestPeriod: "Tutto l'anno dove presente, esclusivamente nelle ore di luce per i suggerimenti visivi. Mattino e tardo pomeriggio offrono spesso luce più morbida.",
    diet: "Piccoli mammiferi, insetti e altri piccoli vertebrati secondo habitat e stagione.",
    breeding: "Usa cavità, edifici e vecchi nidi; non costruisce normalmente un proprio nido di rami.",
    voiceDescription: "Richiamo acuto e ripetuto, spesso territoriale o d'allarme. Non attirarlo con playback.",
    tags: ["Prati e coltivi", "Rupi", "Periferie"], seasons: ["Mar–Mag: attività territoriale nelle ore di luce; rispetta i nidi.", "Giu–Ago: giovani e caccia nei prati; mattino e tardo pomeriggio.", "Set–Nov: movimenti e migrazione; osserva i campi e i posatoi.", "Dic–Feb: presente in molte zone; usa le ore luminose."], seasonLevels: [3, 3, 3, 2],
    newArtwork: true,
    signs: [("Impronta","Orma da rapace con artigli; non è sufficiente per distinguere un falco."),("Fatte","Urati chiari e parte scura; sotto i posatoi possono esserci anche borre."),("Penne","Penne barrate; confronta con altri falchi senza prelevare il reperto."),("Spirito santo","Volo stazionario sopra aree aperte, coda distesa; non è esclusivo del gheppio.")],
  ),
"Assiolo": SpeciesDetail(
    habitat: "Frequenta mosaici aperti con vecchi alberi e cavità, frutteti, filari, parchi e boschi radi. La disponibilità di insetti e rifugi è importante. In Italia è prevalentemente presente nella stagione calda; alcune popolazioni meridionali e insulari sono sedentarie. Il solo albero vicino non dimostra presenza locale.",
    asset: "assiolo",
    size: "19–20 cm · ali 53–63 cm",
    mass: "58–135 g",
    activity: "Crepuscolo e notte, soprattutto ascolto",
    photo: "Privilegia il crepuscolo con luce naturale. AF-C, appoggio stabile e tempo compatibile con il soggetto; rinuncia se servirebbe disturbarlo.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/assiolo",
    bestPeriod: "Per l'ascolto soprattutto maggio–luglio dopo il tramonto. Osservazione visiva difficile e distinta dal canto; presenze invernali richiedono conferma locale.",
    diet: "Soprattutto grandi insetti, con altri piccoli animali occasionali.",
    breeding: "Nidifica in cavità naturali o artificiali; non sostare davanti al foro.",
    voiceDescription: "Nota breve e flautata, il 'chiù', ripetuta a intervalli regolari. Ascolta in silenzio.",
    tags: ["Filari", "Frutteti", "Boschi radi"], seasons: ["Mar–Mag: arrivo e inizio canto nelle zone occupate; dopo il tramonto.", "Giu–Ago: canto nelle serate miti; ascolta senza playback.", "Set–Nov: migrazione e riduzione delle presenze; eccezioni locali.", "Dic–Feb: generalmente assente al Nord; sedentario solo in parte dell'areale."], seasonLevels: [3, 4, 1, 0],
    newArtwork: true,
    signs: [("Impronta","L'impronta può mostrare due dita avanti e due dietro; la disposizione varia con la presa."),("Borre","Rigurgiti con resti, spesso di insetti; non sono fatte e non bastano a identificare la specie."),("Penne","Piccole penne finemente macchiettate: servono confronto e contesto."),("Mimetismo","Sagoma sottile e piumaggio da corteccia; non cercarlo fra le cavità.")],
  ),
"Nibbio reale": SpeciesDetail(
    habitat: "Cerca cibo sopra prati, pascoli e campagne, alternati ad alberi usati per nidificare o riposare. In Italia la distribuzione è discontinua e cambia tra nidificazione, migrazione e svernamento. Un ambiente compatibile non equivale alla presenza della specie: servono segnalazioni regionali attendibili prima di proporla fra gli incontri prioritari.",
    asset: "nibbio_reale",
    size: "60–66 cm · ali 155–180 cm",
    mass: "Circa 0,8–1,3 kg",
    activity: "Diurno, volo planato",
    photo: "1/1600–1/2500 s in volo, AF-C e area ampia; conserva coda e ali complete nell'inquadratura.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/nibbio-reale",
    bestPeriod: "Ore di luce nelle zone con presenza documentata. Migrazione e svernamento possono offrire opportunità diverse: verifica sempre il contesto regionale.",
    diet: "Carcasse e piccoli vertebrati; risorse variabili secondo il territorio.",
    breeding: "Nido su alberi in mosaici aperti; rispetta anche dormitori e posatoi collettivi.",
    voiceDescription: "Fischi e richiami sottili. Il riconoscimento richiede confronto con il nibbio bruno.",
    tags: ["Prati e pascoli", "Campagne", "Boschetti"], seasons: ["Mar–Mag: migrazione e territorio nelle zone occupate, ore di luce.", "Giu–Ago: nidificazione localizzata; non avvicinarti ai nidi.", "Set–Nov: movimenti autunnali; presenza variabile per regione.", "Dic–Feb: svernamento in alcune aree italiane; non generalizzare al Nord."], seasonLevels: [3, 2, 3, 3],
    newArtwork: true,
    signs: [("Impronta","Orma da rapace; confronta con altri indizi, non attribuirla dalla sola forma."),("Fatte","Deiezioni con urati, talvolta borre sotto i posatoi; non sono diagnostiche."),("Penne","Toni rossicci nella coda; documenta senza raccogliere."),("Coda forcuta","Forcella profonda e rossiccia, con finestre bianche sotto le ali; valuta più caratteri.")],
  ),
"Nibbio bruno": SpeciesDetail(
    habitat: "Frequenta laghi, fiumi e zone umide affiancati da boschi e spazi aperti. Cerca cibo anche su prati e coltivi. In Italia è soprattutto migratore e nidificante nella stagione calda, con distribuzione irregolare. Rari svernamenti non rendono l'inverno una finestra generale: habitat e segnalazioni locali devono concordare.",
    asset: "nibbio_bruno",
    size: "55–60 cm · ali 135–170 cm",
    mass: "600–930 g",
    activity: "Diurno, volo planato",
    photo: "AF-C, 1/2000 s in volo e raffica breve; separa il soggetto dallo sfondo del bosco.",
    source: "https://www.lipu.it/uccelli/conoscerli-proteggerli/nibbio-bruno",
    bestPeriod: "Soprattutto marzo–agosto nelle aree occupate; ore di luce per il volo. Settembre dipende dal passaggio migratorio, inverno solo con conferme locali.",
    diet: "Pesci, piccoli vertebrati, invertebrati e carcasse secondo disponibilità.",
    breeding: "Nidifica su alberi e talvolta rupi, spesso vicino ad ambienti acquatici.",
    voiceDescription: "Fischi e trilli variabili; evita playback e confronta con altri rapaci.",
    tags: ["Fiumi e laghi", "Zone umide", "Boschi ripariali"], seasons: ["Mar–Mag: ritorno migratorio; ore di luce presso fiumi e laghi.", "Giu–Ago: presenza nelle aree riproduttive; resta lontano dai nidi.", "Set–Nov: partenze, soprattutto inizio autunno; poi presenze rare.", "Dic–Feb: in genere assente; eventuali svernamenti sono localizzati."], seasonLevels: [4, 3, 1, 0],
    newArtwork: true,
    signs: [("Impronta","Orma con artigli da rapace: non sufficiente a distinguere la specie."),("Fatte","Urati chiari e parti scure, con possibili borre; considera più indizi."),("Penne","Penne brune; forma e dimensioni vanno confrontate con altri rapaci."),("Coda forcuta","Forcella superficiale, piumaggio bruno e assenza della coda rossiccia del nibbio reale.")],
  ),
};
